name: cv_proj1
channels:
  - conda-forge
  - pytorch
  - python=3.6
dependencies:
  - bandit
  - flake8
  - jupyter
  - matplotlib
  - mypy
  - numpy
  - pytest
  - pyyaml
  - pytorch-cpu
  - torchvision-cpu=0.2